name: Continuous Integration
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./Shared/Shared.sln
    - name: Build
      run: dotnet build ./Shared/Shared.sln --no-restore
    - name: Test
      run: dotnet test ./Shared/Shared.sln --no-build --verbosity normal